# The Trusty beta Build Environment
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt562-trusty
  - sudo apt-get update

install:
  - sudo apt-get install -y qt56base qt56tools #install necessary Qt files

script:
  - source /opt/qt56/bin/qt56-env.sh
  - sh build.sh
